inherit_gem:
  rubocop-discourse: default.yml

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Discourse/TimeEqMatcher:
  Enabled: false

Discourse/NoAddReferenceOrAliasesActiveRecordMigration:
  Enabled: false
