pull_request_title: 'I18n: Update translations'
files:
  - source: /config/locales/client.en.yml
    translation: /config/locales/client.%two_letters_code%.yml
  - source: /config/locales/server.en.yml
    translation: /config/locales/server.%two_letters_code%.yml
