name: Metadata

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout head repository
        uses: actions/checkout@v2

      - name: Store head version
        run: |
          sed -n -e 's/^.*version: /head_version=/p' plugin.rb >> $GITHUB_ENV

      - name: Checkout base repository
        uses: actions/checkout@v2
        with:
          ref: github.base_ref

      - name: Store base version
        run: |
          sed -n -e 's/^.*version: /base_version=/p' plugin.rb >> $GITHUB_ENV

      - name: Fail if version is incorrect
        if: printf '${{ env.head_version }}\n${{ env.base_version }}\n' | sort -V | head -n1 | grep '${{ env.head_version }}'
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Branch version is equal to or lower than base version.')